name: workflows-tests
run-name: ${{ github.actor }} is testing
on: 
    pull_request_target:
        types: [assigned, opened, synchronize, reopened]
    workflow_dispatch:
    workflow_call:
  
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check branch
        run: echo "echo ${GITHUB_REF##*/}"
      - name: check commit
        run : git show $GITHUB_SHA
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      # - run: npm test